# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71cff210dc9cdcf1227fe21e38db0f50513e74d4b814123b374e66939d3928b11c96a852b4a0e188663f780c402a8ceaae29f5ad5026a42b8c533a111c6eecf3

test:
  secret_key_base: b702cefee3c4e8540395bd63c81044c7e530fc80b8a46d7d6f0b170e3dd08e2748dc3dc7ae60563e53eab32cbece20487d1b6af6730a0e959fe528b0be9b7444

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
